version: "3.0"
services:
  cyber-dice-server:
    build: ./server/.
    ports:
      - "5000:5000"
    volumes:
      - "./file_uploads:/app/uploads"
    networks:
      - "cyberdice"
  cyber_dice_database:
    image: postgres
    restart: always
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    networks:
      - "cyberdice"

networks:
  cyberdice: